### ISSUE TITLE
Add ability to output computed variables

### ISSUE THREAD

**Issue by bisgardo** [bisgardo/github-action-regex-parse#13]
For example
```
            - name: Parse tag name
              uses: bisgardo/github-action-regex-parse@v1
              id: tag
              with:
                  pattern: "(?<name>(?<package>.*?)/(?<version>.*))"
                  input: "${{steps.ref.outputs.ref-name}}"
```
could be extended to also define `workspace` as a variable computed from the match of `package` by something like:
```
            - name: Parse tag name
              uses: bisgardo/github-action-regex-parse@v1
              id: tag
              with:
                  pattern: "(?<name>(?<package>.*?)/(?<version>.*))"
                  input: "${{steps.ref.outputs.ref-name}}"
                  extra-outputs: |
                    workspace=@org/$package
```

However, the notation would probably have to nicer for this to be worth it compared to making this a separate action (or just writing to `$GITHUB_OUTPUT` in a subsequent step)...
